workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        instance_type: mac_mini_m1
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk

            
